### ISSUE TITLE
Testing using expo app

### ISSUE THREAD

**Issue by ismaelrumzan** [includable/react-native-map-link#44] opened 2018-10-06 11:01 UTC
Hi
Thanks for this plug-in - working nice
I'm building the app using expo and react native.
When I use the function showLocation, although I have put three apps in the whitelist options (google maps, apple maps and uber), it opens directly in apple maps. I've tried both in simulator and expo app on a device

**Comment by tschoffelen** [comment] 2018-10-06 11:17
Please see #39.

**Comment by amsimoes** [comment] 2018-11-06 16:44
Hello all,

I'm also developing on Expo, and it's possible to edit the info.plist file, by adding what's needed for it on the app.json file. And then when building (with expo:build ios, never ejecting) the .ipa file has the info.plist which I checked and it has the right syntax:

```
<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>comgooglemaps</string>
		<string>citymapper</string>
		<string>uber</string>
		<string>lyft</string>
		<string>waze</string>
	</array>
```

Which gets produced by writing on app.json like this (on Expo):
```
"ios": {
    "infoPlist": {
          "LSApplicationQueriesSchemes": ["comgooglemaps", "citymapper", "uber", "lyft", "waze"]
    }
}
```

Problem is, I haven't been able to see Google Maps, and other installed apps, on the Popup. I only get to see Apple Maps.
But when using the option `app: 'google-maps'`, I'm able to open Google Maps as intended.

Checking other installed apps it's the problem, on iOs (haven't tested on Android yet) with info.plist configured correctly as required.

Any hint on fixing this?

Thank you!

**Comment by tschoffelen** [comment] 2018-11-08 09:39
How are you running the app? Within the Expo app, or compiling it separately?

**Comment by amsimoes** [comment] 2018-12-13 13:16
I've just tested it after building a standalone app (fully using Expo, not detached), and this lib works as intended :) 

Meaning that editing info.plist on app.json (Expo way), it then works on the app built using expo.

**Comment by tschoffelen** [comment] 2018-12-13 13:38
@amsimoes Great to hear! Would indeed love it if you could submit a PR to add something to README.md about this. Or perhaps a separate markdown file that we link to from readme.

**Comment by ismaelclass** [comment] 2018-12-21 17:06
@amsimoes I tried the app.json way and uber shows up. This is what I have in the app.json
      "infoPlist": {
        "LSApplicationQueriesSchemes": ["google-maps", "uber", "apple-maps","citymapper", "lyft", "waze"]
      }
And on my phone, only google maps, uber and apple maps are installed.
Apple maps and uber show up but not google maps.
Any ideas?

**Comment by tschoffelen** [comment] 2018-12-21 20:05
Hi @ismaelclass, that's because the URL scheme for Google Maps is `comgooglemaps`, not `google-maps`.

Have a look at the documentation that I've just added: [expo.md](https://github.com/includable/react-native-map-link/blob/master/docs/expo.md).

Also hereby closing this issue for now, since the README has been updated with additional instructions. If there are any separate issues resulting from any of this, please feel free to open a new issue.

**Closed by tschoffelen** 2018-12-21 20:05 UTC
Labels: duplicate
