### ISSUE TITLE
Open google maps sending street and city name

### ISSUE THREAD

**Issue by Bocci94** [includable/react-native-map-link#27] opened 2018-06-04 20:57 UTC
Hi, is possible (with this) to open maps writing street and city? Instead of lat and long

**Comment by tschoffelen** [comment] 2018-06-04 21:14
Duplicate of #5.

**Comment by tschoffelen** [comment] 2018-06-07 18:04
Closing this one since it is a duplicate of #5. Nevertheless, this might still be something that we might build in the near future, so please subscribe to #5 to stay up to date.

**Closed by tschoffelen** 2018-06-07 18:04 UTC
