### ISSUE TITLE
IOS 11 Issue - App Selection suddenly disappears

### ISSUE THREAD

**Issue by rey-an-papa-ext** [includable/react-native-map-link#33] opened 2018-07-12 15:12 UTC
Hi,

I used react-native-map-link where I just pass the origin and destination longitude and latitude. Everthing is ok in Android but I encountered an issue in IOS where it shows the modal of the available Map applications but it suddenly disappears in 1-2 second then the app hangs.

Here's my implementation:
<img width="840" alt="screen shot 2018-07-13 at 1 33 47 pm" src="https://user-images.githubusercontent.com/19182530/42674246-7c9e0ac8-86a1-11e8-8177-21725524337c.png">

Hoping for your assistance on this.

**Comment by tschoffelen** [comment] 2018-09-03 08:45
Closing this issue for now as I can't reproduce it and more info isn't supplied.

**Closed by tschoffelen** 2018-09-03 08:45 UTC
Labels: bug, needs info
